-- MySQL Script generated by MySQL Workbench
-- 05/21/17 13:47:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_tiendaFlores
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_tiendaFlores
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_tiendaFlores` DEFAULT CHARACTER SET utf8 ;
USE `bd_tiendaFlores` ;

-- -----------------------------------------------------
-- Table `bd_tiendaFlores`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tiendaFlores`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tiendaFlores`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tiendaFlores`.`marcas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tiendaFlores`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tiendaFlores`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `precioCompra` DECIMAL(19,7) NOT NULL,
  `precioVenta` DECIMAL(19,7) NOT NULL,
  `Productocol` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `stock` INT NOT NULL,
  `unidad` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(50) NULL,
  `estado` VARCHAR(45) NOT NULL,
  `presentacin` VARCHAR(45) NOT NULL,
  `categoria_id` INT NOT NULL,
  `marcas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Producto_categoria1_idx` (`categoria_id` ASC),
  INDEX `fk_producto_marcas1_idx` (`marcas_id` ASC),
  CONSTRAINT `fk_Producto_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `bd_tiendaFlores`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_marcas1`
    FOREIGN KEY (`marcas_id`)
    REFERENCES `bd_tiendaFlores`.`marcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tiendaFlores`.`tipoPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tiendaFlores`.`tipoPago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tiendaFlores`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tiendaFlores`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(80) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `apellidos` VARCHAR(50) NULL,
  `fechCrea` DATETIME NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `admin` TINYINT(1) NOT NULL DEFAULT 0,
  `dni` INT NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tiendaFlores`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tiendaFlores`.`venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `serieComprobante` VARCHAR(11) NOT NULL,
  `fechaPedido` DATETIME NOT NULL,
  `fechaVenta` DATETIME NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `total_venta` DECIMAL(19,7) NOT NULL,
  `Tipo_pago_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Venta_Tipo_pago1_idx` (`Tipo_pago_id` ASC),
  INDEX `fk_venta_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_Venta_Tipo_pago1`
    FOREIGN KEY (`Tipo_pago_id`)
    REFERENCES `bd_tiendaFlores`.`tipoPago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bd_tiendaFlores`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tiendaFlores`.`tipoOperacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tiendaFlores`.`tipoOperacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_tiendaFlores`.`detalleVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_tiendaFlores`.`detalleVenta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` VARCHAR(45) NOT NULL,
  `subtotal` DECIMAL(19,7) NOT NULL,
  `precio_venta` DECIMAL(19,7) NOT NULL,
  `descuento` DECIMAL(19,7) NOT NULL,
  `Producto_id` INT NOT NULL,
  `Venta_id` INT NOT NULL,
  `tipoOperacion_id` INT NOT NULL,
  `fechCreac` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_DetalleVenta_Producto1_idx` (`Producto_id` ASC),
  INDEX `fk_DetalleVenta_Venta1_idx` (`Venta_id` ASC),
  INDEX `fk_detalleVenta_tipoOperacion1_idx` (`tipoOperacion_id` ASC),
  CONSTRAINT `fk_DetalleVenta_Producto1`
    FOREIGN KEY (`Producto_id`)
    REFERENCES `bd_tiendaFlores`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleVenta_Venta1`
    FOREIGN KEY (`Venta_id`)
    REFERENCES `bd_tiendaFlores`.`venta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleVenta_tipoOperacion1`
    FOREIGN KEY (`tipoOperacion_id`)
    REFERENCES `bd_tiendaFlores`.`tipoOperacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
